apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-d46c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-d46c"
  template:
    metadata:
      labels:
        app: "myakscluster-d46c"
    spec:
      containers:
        - name: "myakscluster-d46c"
          image: "auodep.azurecr.io/myakscluster"
          ports:
          - containerPort: 80